moleculerjs/moleculer-db

packages/moleculer-db-adapter-mongoose/src/index.js
packages/moleculer-db-adapter-mongoose/test/models/posts.js
packages/moleculer-db-adapter-mongoose/test/unit/index.spec.js

Mongoose adapter will now allows schema as option to be passed for services. This allows for use cases where we need to create models dynamically @see https://github.com/ice-services/moleculer-db/pull/5

Mongoose schema

---

packages/moleculer-db/src/index.js

Get function is not passing in the sanitized params when calling transformDocuments where, the list function does. This causes a bug where when passing in ?populate=fieldname in query string to not populate. The populateDoc function expects an array.

Pass in params instead of ctx.params

---

packages/moleculer-db/src/index.js
packages/moleculer-db/test/unit/index.spec.js

When you use `RedisCacher`, and you do `get` and just after `update` on a service with a model, sometime you will get the older cached value.
And after a little of troubleshoot, i find that any update/delete action do not wait for cache to clear before returning the action. (Not visible with memory cacher because synchronous)
The little fix it's to return the promise of `this.broker.cacher.clean` in the `clearCache` function.
And it was fix.

fix: Wait for cache clear

---

packages/moleculer-db/src/index.js
packages/moleculer-db/test/unit/index.spec.js

When a service has a version number then its cache is being saved as v1.service.find instead of service.find
this version number of the service is present in fullName if a version number is used, otherwise fullName only contain name of service. So using fullName instead of name in clearCache resolves this problem.

UPDATE: cache clear bug resolved

---

packages/moleculer-db/src/index.js

In moleculer-db package, in index.js, the populateDocs function validates the docs parameter incorrectly, using an || forcing the parameter to be an array. By using an && it allows for the intended types of object or array.

fix: docs validation in populateDocs

---

packages/moleculer-db/examples/simple/index.js

Hi,
Before everything else, I noticed a failed test in examples/single/index.js. It is caused by a date comparison returning false and the solution I've found (on StackOverflow :P) is to rely on date.getTime() instead of comparing date objects.
https://stackoverflow.com/questions/492994/compare-two-dates-with-javascript
Best,
Razvan

Fixed date comparison in CREATE new post test

---

packages/moleculer-db-adapter-sequelize/src/index.js
packages/moleculer-db-adapter-sequelize/test/unit/index.spec.js

You are able to set a new config property "noSync", when creating a new instance of SqlAdapter.
`new SqlAdapter(credentials.database, credentials.user, credentials.password, {  
host: credentials.host,  
dialect: "mysql",  
pool: {  
max: 5,  
min: 0,  
idle: 10000  
},  
define: {  
// logging: false,  
timestamps: false,  
freezeTableName: true  
},  
noSync: true  
})`
If the property is set to true, the model will not be synced by Sequelize.
If your database user doesn't have permission to create a table, SQL will throw an error and you can't use this adapter.
If the "noSync" property is not provided, nothing will change to the previous logic.

added noSync to SqlAdapter

---

packages/moleculer-db/package-lock.json
packages/moleculer-db/src/index.js
packages/moleculer-db/test/unit/index.spec.js

Hi,
This PR allows to populate nested fields using `lodash` setters and getters.
Should fix #124

Handle nested field populate

---

packages/moleculer-db-adapter-sequelize/src/index.js
packages/moleculer-db-adapter-sequelize/test/unit/index.spec.js

Get sync option from sequelize connection config https://github.com/sequelize/sequelize/blob/5a807c514c00364d0fcd56ae682a06750c398df8/types/lib/sequelize.d.ts#L271
Useful when we have one config file for run migrations(https://sequelize.org/master/manual/migrations.html) and connect to db in molecular

feat: use sync option from sequelize config for disable/enable sync model

---

packages/moleculer-db-adapter-mongoose/src/index.js
packages/moleculer-db-adapter-mongoose/test/unit/index.spec.js

When searchFields exists, do a "LIKE" search based on searchFields, when not, uses the full-text search based on index as it is currently. This would not break existing functionality, since without searchFields the search will work as it currently does and will allow the adapter to work like the others when searchFields is informed.
Related to #196

Add support for searchFields parameter in the moleculer-db-adapter-mongoose

---

packages/moleculer-db-adapter-sequelize/src/index.js
packages/moleculer-db-adapter-sequelize/test/unit/index.spec.js

Change method signature from `insertMany(entities)` to `insertMany(entities, opts = { returning: true })` to allow passing in of custom options, eg. `ignoreDuplicates`

sequelize adaptor insertMany to accept an options object

---

packages/moleculer-db-adapter-mongoose/package-lock.json
packages/moleculer-db-adapter-mongoose/package.json
packages/moleculer-db-adapter-mongoose/src/index.js

Fix this issue #221 
When using mongoose v5.10.1 or later, we will get this error if there is more than one service.
Probably caused by this commit: [Automattic/mongoose@fadc813](https://github.com/Automattic/mongoose/commit/fadc813eaa32dd357e93beb8614de35e5f346600) - [History.md](https://github.com/Automattic/mongoose/blob/master/History.md#5101--2020-08-26)
To reproduce the error, I am using mongoose v5.10.5 and run `npm run dev moleculer-db-adapter-mongoose populates`. 
Result:
```
...
[2020-09-17T16:12:48.051Z] INFO desktop-4eps3u4-13761/POSTS: MongoDB adapter has connected successfully.
[2020-09-17T16:12:48.052Z] ERROR desktop-4eps3u4-13761/USERS: Connection error! TypeError: Cannot read property 'connection' of undefined
at …
```

fix connection error if there is more than one service

---

packages/moleculer-db/src/index.js
packages/moleculer-db/test/integration/populates.spec.js

I would like to add this feature that allows to specify the resulting populated field name
```
name: "posts",
adapter: new Adapter(),
settings: {
fields: ["_id", "title", "content", "author","reviewer", "reviewerId"],
populates: {
author: {
action: "users.get"
},
reviewerId: {
field: "reviewer",
action: "users.get"
}
}
}
```
Instead of replacing reviewerId by the resulting populated object, a new field "reviewer" will be added that contains the populated object.
The reason for this feature is that when replacing the original reviewerId field it breaks the contract towards depending services.
Depending services would expect a field reviewerId which contains the reviewer Id as string.
If the reviewerId field is replace by an object, depending service will break on this.
solves issue #223

feat: allow to specify resulting populated field name

---

packages/moleculer-db-adapter-sequelize/package-lock.json
packages/moleculer-db-adapter-sequelize/package.json
packages/moleculer-db-adapter-sequelize/src/index.js
packages/moleculer-db-adapter-sequelize/test/unit/index.spec.js

This PR is relative to the issue #227.
Trying to solving the issue highlighted by #227 : with this PR, after a connection error inside the Sequelize adapter, the Sequelize instance is shot down avoiding creating memory leaks for unreferenced database connections and avoiding too many connections to the database itself when retrying.
Added one new test for checking if the Sequelize.close gets closed after an instantiation error is thrown.
Added @types/jest in dev dependencies.

[hacktoberfest] Close Sequelize before connection error

---

package-lock.json
package.json
packages/moleculer-db/src/index.js

when call throw action list, the params is passed `sanitizeParams` that correct `params.limit`, after that, params will be sent to `adapter.find` but if we make directly call `this._list` method, params was not done properly and missing `limit` property.
this pull fix this problem
more fixes:
~~+ missing flat, nedb packages that prevent me running test~~
+ eslint check `'flat'` to `"flat"`

fix missing limit when directly call this._list(ctx, params)

---

packages/moleculer-db-adapter-mongoose/src/index.js

`mongoose.connection` always point to `mongoose.connections[0]` so if we call sth likes
```js
return {
mixins: [DbService],
adapter: new MongoAdapter('mongodb://127.0.0.1') // new connection was created each service
}
```
we can not disconnect correctly (because we just stop first connection)
this pull fix this problem

fix mongoose stuck after broker.stop called

---

packages/moleculer-db/package.json
packages/moleculer-db/src/memory-adapter.js
packages/moleculer-db/test/unit/memory-adapter.spec.js

Allow MemoryAdapter to use a datastore that already exists instead of creating one during the connect call

Use preconfigured Nedb Datastore instead of creating one

---

packages/moleculer-db-adapter-mongo/src/index.js

if you had a _id string that was 12 characters long and not hex, it would fail as its not a hex string.  If it is not an actual hex string fall back to the other method

allow 12 character _ids to be processed

---

packages/moleculer-db-adapter-mongoose/index.d.ts

`MongooseDbAdapter` should match with `DbAdapter` in `moleculer-db`
Usage:
```typescript
import type { MoleculerDB } from 'moleculer-db';
import type MongooseDbAdapter from 'moleculer-db-adapter-mongoose';
import type { Document } from 'mongoose';
type Type = MoleculerDB<MongooseDbAdapter<Document>>;
```

Update moleculer-db-adapter-mongoose type define

---

packages/moleculer-db-adapter-mongoose/index.d.ts

`ConnectionBase` in mongoose .d.ts file is not use or export
And in special, mongoose not export this in latest version.
If user install latest mongoose, it have a type error
Reference: https://github.com/Automattic/mongoose/blob/master/index.d.ts

Remove useless code in moleculer-db-adapter-mongoose tsd

---

packages/moleculer-db/src/index.js
packages/moleculer-db/test/unit/index.actions.spec.js

call `sanitizeParams` is unnecessary for `insert` and `remove`

remove unnecessary sanitizeParams

---

packages/moleculer-db-adapter-mongoose/index.d.ts

Removed unused import from ```moleculer-db-adapter-mongoose``` typings file, was giving an error in my environment where I don't generate code until code is completely clean.

Updated Imports in typings file

---

packages/moleculer-db-adapter-mongoose/src/index.js
packages/moleculer-db-adapter-mongoose/test/unit/index.spec.js

fix mongoose search with query.$or
problem: `cursor.find({ $or: {/* */} })` will overwrite `params.query.$or`
solution: if `query.$or` is existed, push both to `query.$and`

fix mongoose search with query.$or

---

packages/moleculer-db/moleculer-db.d.ts

- both service methods `_get` and `_list` required params
- fix: _get params only required `id` fields, another fields is optional

correct params for _get, _remove

---

packages/moleculer-db/src/index.js
packages/moleculer-db/test/unit/index.spec.js

Fixed async validation errors (issue #305).
If you try without the new update will always be thrown a validation error without any data, because on
```js
let res = check(entity);
if (res === true)
return Promise.resolve();
```
if you are using an async custom validation ```res``` will be equal to *Promise{<fullfilled/rejected>, true/data}*
For detecting that's an async function it's used the ```async``` property, like said in the docs of [Fastest Validator](https://github.com/icebob/fastest-validator#asynchronous-custom-validations), if using another type of validator check the presence of ```then``` function
```js
if (check.async || (res.then) instanceof Function) res = await res;
```

fix #305 - Async custom validation

---

packages/moleculer-db-adapter-sequelize/src/index.js
packages/moleculer-db-adapter-sequelize/test/unit/index.spec.js

Apply a more explicit count of data for the pagination, normally there's no problem but when doing an ```include``` in the default scope will be counted the included data for each record. For example:
By having those two models
```js
let User = sequelize.define("users",
{
id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
username: { type: DataTypes.STRING }
}, { paranoid: true }
);
```
```js
let Auth = sequelize.define("auths",
{
id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
name: { type: DataTypes.STRING }
}, { paranoid: false }
);
```
and they have a relation like this
```js
Auth.belongsTo(models["users"], {
foreignKey: "user_id",
as: "users"
});
```
When trying to get all users with this defaultScope
```js
User.associate = function …
```

fix: count just the right number of row

---

packages/moleculer-db-adapter-mongoose/src/index.js

I figure, with bad username / password ( or bad encoded ), `this.db` is undefined on line 109 .
But it log a success, and an error because `this.db` is undefined . 
This change will just throw an error before telling all is OK ( checking readyState ) . And throwing another error, just in case `this.db` is not defined

Mongoose : add a more readable error

---

packages/moleculer-db/src/index.js
packages/moleculer-db/test/integration/idField.test.js

This is a follow-up bug from #254 . It was supposed to be fixed then, but I got the same issue today. To reproduce, simply use one of the tests in the commit without the fix. The _get method with _mapping: true fails with custom idFields and returns undefined for the mapping key. Since that is what is used during population, population is also broken, which could fix issues #325 and #296.
The problem was the line origDoc = doc, which did not truly copy the document, simply assigned it by reference. Our reference to the original document was thus lost during transformDocument method, as doc variable is mutated there.

Fix bug - populate not working - idField mapped to undefined (issue #325, maybe #296)

---

packages/moleculer-db/src/index.js
packages/moleculer-db/test/integration/populates.spec.js
packages/moleculer-db/test/unit/index.spec.js

📝 Description
This allows to recursively populate fields. Example:
if
```
postsService.settings.populates = {
author: "users.get",
reviewer: "users.get",
"liked.by": "users.get"
};
usersService.settings.populates = {
group: "groups.get"
};
```
Then it is now possible to populate groups from a posts query like this:
```
const post = await posts.get({
id: postId,
populate: ["author.group", "reviewer.group", "liked.by.group"]
})
post.author.group.name //populated;
post.reviewer.group.name //populated;
post.liked.by.group.name //populated;
```
🎯 Relevant issues
No issue that I know of
💎 Type of change
New feature (non-breaking change which adds functionality)
🚦 How Has This Been Tested?
🏁 Checklist:

feat: Recursive deep populate

---

packages/moleculer-db/src/index.js
packages/moleculer-db/test/unit/index.methods.spec.js
packages/moleculer-db/test/unit/index.spec.js

Runs a lifecycle event before an entity is created, updated or removed. Right now, we only have entityCreated, entityUpdated and entityRemoved, which run AFTER the entity change.
Having a lifecycle event before allows for a better handling of createdAt and updatedAt data fields. In the [docs](https://moleculer.services/docs/0.14/moleculer-db.html#Data-Manipulation), it is said hooks can be used for that purpose, however, hooks are only run before actions, not methods. Using this._create, this._insert, this._update or this._remove would bypass the hook, leaving the createdAt and updatedAt fields empty.
No issue that I know of

Feature proposal - BeforeEntity(Change|Update|Remove) lifecycle events

---

packages/moleculer-db/src/index.js
packages/moleculer-db/test/unit/index.spec.js

https://github.com/moleculerjs/moleculer-db/blob/f26871e4429190b4199805065b005c41112bcb5c/packages/moleculer-db/src/index.js#L593
if `settings.fields = [...,"author.user.name"]`, and client asked for `fields = "user"` will return unwanted `author` field

fix authorize fields unsafe check

---

packages/moleculer-db-adapter-mongo/index.d.ts
packages/moleculer-db-adapter-mongo/package.json

We ran into an issue in our TypeScript code when we tried to use moleculer-db-adapter-mongo 0.4.16, because the TypeScript signature did not match the JavaScript code.

Fix constructor signature of MongoDB adapter in TypeScript

---

packages/moleculer-db/src/index.js

I forgot to merge `settings.excludeFields` with client `params.excludeFields`

fix(excludeFields): prevent client from bypassing settings.excludeFields

---

packages/moleculer-db-adapter-mongoose/README.md

- updates the version of `mongoose` displayed in the README install instructions for using `moleculer-db` and `moleculer-db-adapter-mongoose` to the correct version supported in version 9+

Update Mongoose Adapter Readme

---

.vscode/launch.json
packages/moleculer-db-adapter-mongoose/src/index.js
packages/moleculer-db-adapter-mongoose/test/unit/index.spec.js

This PR is here to fix #361 . 
It seems that, after calling on time `mongoose.connect` . The "connection" promise is available in "mongoose.connection.$initialConnection"
So, the promise will wait one, or the other . 
and I reuse the commons objects from mongoose to setup current connection, events handler, and other . 
tested with mongoose@^6 and mongoose@^7

fix(moleculer-db-adapter-mongoose): remove connecting error/warning, Fix #361

---

packages/moleculer-db/src/index.js
packages/moleculer-db/src/utils.js
packages/moleculer-db/test/unit/index.spec.js

use `.$.` to deeply filter fields in array elements
please look at test
`cars.$.wheels.$.histories.$.date` is used to get `date` property of `histories`, which is an array property of `wheels` - which, again, is an array property of `cars`

feat: allow filter object fields inside an array

---

packages/moleculer-db-adapter-mongoose/README.md
packages/moleculer-db-adapter-mongoose/src/index.js
packages/moleculer-db-adapter-mongoose/test/integration/virtuals.spec.js
packages/moleculer-db-adapter-mongoose/test/models/users.js
packages/moleculer-db-adapter-mongoose/test/unit/index.spec.js

I've separated, in a dedicated method, the code that handles the virtuals population. It allows the code to be more readable and easier to unit test.
Also I've included some short-circuits to avoid useless overhead and keep the virtual step as fast as possible, especially when it need to be bypassed.
Now, You can also disable the virtual population mechanism by adding `{virtuals: false}` in the service settings (request made by @thib3113). Note that letting the service decide by itself is now nearly as fast as adding this option.
You can now override populate options for each virtuals separately by providing an object in the service `settings.virtuals`.
example:
```js
{
virtuals: {
myVirtual: {
select: "foo bar baz",
options: { lean: false },
transform: (doc) => doc,
}
}
}
```
I recently …

Create an adapter method to handle virtual population

---

packages/moleculer-db-adapter-mongoose/package-lock.json
packages/moleculer-db-adapter-mongoose/package.json
packages/moleculer-db-adapter-mongoose/src/index.js

This PR removes the no longer supported `bluebird` package from mongoose adapter.
See [deprecation warning](https://github.com/petkaantonov/bluebird/?tab=readme-ov-file#%EF%B8%8Fnote%EF%B8%8F)

Remove bluebird from moleculer-db-adapter-mongoose

---

packages/moleculer-db-adapter-mongo/examples/integration/index.js
packages/moleculer-db-adapter-mongo/examples/simple/index.js
packages/moleculer-db-adapter-mongo/package-lock.json
packages/moleculer-db-adapter-mongo/package.json
packages/moleculer-db-adapter-mongo/src/index.js

This PR removes the no longer supported `bluebird` package from mongo adapter.
It also replace `let` statements with `const` statement when possible.
See [deprecation warning](https://github.com/petkaantonov/bluebird/?tab=readme-ov-file#%EF%B8%8Fnote%EF%B8%8F)

Remove bluebird from moleculer-db-adapter-mongo

---

packages/moleculer-db-adapter-mongoose/src/index.js
packages/moleculer-db-adapter-mongoose/test/unit/index.spec.js

As of mongoose v8 [Model.findByIdAndRemove()](https://mongoosejs.com/docs/7.x/docs/api/model.html#Model.findByIdAndRemove()) has been deprecated. Since [Model.findByIdAndDelete()](https://mongoosejs.com/docs/api/model.html#Model.findByIdAndDelete()) provides the same functionality, and is present in all versions (v5 to v8) this PR does the drop in replacement.

Replace deprecated findByIdAndRemove with findByIdAndDelete

---

packages/moleculer-db-adapter-sequelize/examples/integration/index.js
packages/moleculer-db-adapter-sequelize/examples/simple/index.js
packages/moleculer-db-adapter-sequelize/package-lock.json
packages/moleculer-db-adapter-sequelize/package.json
packages/moleculer-db-adapter-sequelize/src/index.js

This PR removes the no longer supported `bluebird` package from sequelize adapter.
It also replace `let` statements with `const` statement when possible.
See [deprecation warning](https://github.com/petkaantonov/bluebird/?tab=readme-ov-file#%EF%B8%8Fnote%EF%B8%8F)

Remove bluebird from moleculer-db-adapter-sequelize

---

packages/moleculer-db-adapter-couchdb-nano/examples/integration/index.js
packages/moleculer-db-adapter-couchdb-nano/examples/simple/index.js
packages/moleculer-db-adapter-couchdb-nano/package-lock.json
packages/moleculer-db-adapter-couchdb-nano/package.json
packages/moleculer-db-adapter-couchdb-nano/src/index.js

This PR removes the no longer supported `bluebird` package from couchdb nano adapter.
See [deprecation warning](https://github.com/petkaantonov/bluebird/?tab=readme-ov-file#%EF%B8%8Fnote%EF%B8%8F)

Remove bluebird from moleculer-db-adapter-couchdb-nano

---

proposal/moleculer-db-adapter-knex/examples/simple/index.js
proposal/moleculer-db-adapter-knex/src/index.js

This PR removes the no longer supported `bluebird` package from knex adapter.
It also replace `let` statements with `const` statement when possible.
See [deprecation warning](https://github.com/petkaantonov/bluebird/?tab=readme-ov-file#%EF%B8%8Fnote%EF%B8%8F).

Remove bluebird from moleculer-db-adapter-knex

---

packages/moleculer-db-adapter-mongoose/package-lock.json
packages/moleculer-db/examples/encode/index.js
packages/moleculer-db/examples/pagination/index.js
packages/moleculer-db/examples/populates/index.js
packages/moleculer-db/examples/simple/index.js
packages/moleculer-db/package-lock.json
packages/moleculer-db/package.json
packages/moleculer-db/src/index.js
packages/moleculer-db/src/memory-adapter.js
packages/moleculer-db/test/checker.js

This PR removes the no longer supported `bluebird` package from moleculer-db.
It also replace `let` statements with `const` statement when possible.
See [deprecation warning](https://github.com/petkaantonov/bluebird/?tab=readme-ov-file#%EF%B8%8Fnote%EF%B8%8F).
I also ran `npm audit fix` to apply available CVE fixes.

Remove bluebird from moleculer-db

---

.github/workflows/ci.yml
packages/moleculer-db-adapter-mongoose/package-lock.json
packages/moleculer-db-adapter-mongoose/package.json
packages/moleculer-db-adapter-mongoose/src/index.js
packages/moleculer-db-adapter-mongoose/test/unit/index.spec.js
packages/moleculer-db/test/checker.js

I'm recreating this PR as the preceding one has been automatically closed while resyncing my fork.
I've refactorized `connect()` and `disconnect()` methods from mongoose adapter to be compatible with mongoose 6, 7 and 8.
I've checked that it worked properly by running the tests after installing each versions (6, 7, 8) of mongoose locally in the adapter repo.
I have tried to make tests run against mongoose 7 and 8 but it's a complete mess using old version of lerna.
I propose to merge it like that and add mongoose 7 and 8 tests once the npm workspaces refacto is done.

Make mongoose adapter compatible with mongoose 6, 7 and 8

---

packages/moleculer-db/package-lock.json
packages/moleculer-db/package.json
packages/moleculer-db/src/index.js
packages/moleculer-db/src/utils.js
packages/moleculer-db/test/unit/utils.spec.js

This PR removes the `flat` npm package to replace the flattening function by an homemade one that only flattens plain old javascript objects and let other structures as is.
fixes #401

fix: use own object flattening function that supports class objects

---

packages/moleculer-db/src/index.js

After integrating the case-insensitive search in Sequelize I forgot to add the cache's keyword and param validation for the iSearch parameter

Case insensitive search caching
